package com.tschuchort.kotlinelements.mixins


import javax.lang.model.element.ExecutableElement

/**
 * Mixin interface for KotlinElements that have a synthetic
 * `elementName$annotations$ method to hold annotations for the
 * element.
 */
interface HasSyntheticMethodForAnnotations {
	/**
	 * A synthetic method element that may be generated by the Kotlin compiler
	 * to hold annotations of the element if it has any
	 */
	val javaAnnotationHolderElement: ExecutableElement?
}